f = open('24/24_21421.txt').readline()
f = f.replace('C', ' ')
f = f.replace('D', ' ')
f = f.replace('E', ' ')
f = f.replace('F', ' ')
f = f.replace('G', ' ')
f = f.replace('H', ' ')
f = f.replace('I', ' ')
f = f.replace('J', ' ')
f = f.replace('K', ' ')
f = f.replace('L', ' ')
f = f.replace('M', ' ')
f = f.replace('N', ' ')
f = f.replace('O', ' ')
f = f.replace('P', ' ')
f = f.replace('Q', ' ')
f = f.replace('R', ' ')
f = f.replace('S', ' ')
f = f.replace('T', ' ')
f = f.replace('U', ' ')
f = f.replace('V', ' ')
f = f.replace('W', ' ')
f = f.replace('X', ' ')
f = f.replace('Y', ' ')
f = f.replace('Z', ' ')
f = f.split()
maxi=0
for i in f:
    if len(i)> maxi:
        maxi=len(i)
        print(i, len(i))
# 19